services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama-1
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped

  api:
    image: ai_powered_customer_support_assistant:latest
    container_name: ai_powered_customer_support_assistant
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./app:/app
    restart: unless-stopped

volumes:
  ollama_data: